### ISSUE TITLE
why is specs in config.json not being picked up when I run the command?

### ISSUE THREAD

**Issue by huih1108** [mtbikerj/RasaDocker#2]
Hi Jason!

Thanks for putting the tutorial together and it is very helpful!!!!!

I have one question though.

For config.json, it doesn't seem like terminal is picking up the path to models or where the training data is located.

My solution is to write another config file in yml with specified pipeline. But I will still have to indicate the path to training data and the path to model output file in command line. 

Do you know why the JSON file doesn't work?

**Comment by mtbikerj** [comment]
Yes, I found that RASA version 0.12.0 had a change that broke the old usage of config.json.  config.json cannot set the data directory anymore and it needs to be set manually when you run the command.  Including "-d data/train.md" in the command line should solve the issue.

As of version 0.12.0 the terminal command now needs to include the data directory
```
python -m rasa_nlu.train -c config.json -d data/train.md
```
