### ISSUE TITLE
Upgrade to latest rasa core release

### ISSUE THREAD

**Issue by sumanthkulkarni13** [mtbikerj/RasaDocker#4]
Hi, 
Excellent setup to learn. 
Just thought to ask if you can find sometime to update the repos to be compatible with rasa core 11. 

Thanks!

**Comment by mtbikerj** [comment]
Thanks!  I'll definitely upgrade for core 11.  I'm also in the process of putting together an expanded setup for use in Kubernetes.

**Comment by rachamaduguravi** [comment]
Hi, I am having trouble using the latest builds in the tutorial. Please might you share which https://hub.docker.com/r/rasa/rasa_core/tags/ and which https://hub.docker.com/r/rasa/rasa_nlu/tags/ was used in the project? Thanks!

**Comment by mtbikerj** [comment]
@rachamaduguravi - I believe the tutorials should work up to rasa_core v0.11.12 and rasa_nlu v.0.12.3.  I plan on having the tutorial and all branches on this repository updated to work with the most recent versions by tomorrow.

**Comment by mtbikerj** [comment]
Sorry, this ended up being much more difficult, requiring a deep re-write due to breaking changes of the RASA library on almost everything.  I am still working on this and hope to have some updates soon.

**Comment by mtbikerj** [comment]
Updated with some major changes to both the tutorial and this repo.  This should work now with the most recent version of RASA NLU and core.
